import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'svgmap/dist/svgMap.min.css';
import SessionProvider from "@/utils/SessionProvider";
import { getSiteSettings } from "@/lib/site-settings";
import Providers from "@/Providers";
import SessionTimeoutWrapper from "@/components/SessionTimeoutWrapper";
import LenisScrollWrapper from "@/components/LenisScrollWrapper";
import ConditionalLayout from "@/components/ConditionalLayout";
import GlobalLoadingBar from "@/components/GlobalLoadingBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F8F9FA]`}>
        <Suspense fallback={null}>
          <GlobalLoadingBar />
        </Suspense>
        <LenisScrollWrapper>
          <SessionProvider>
            <SessionTimeoutWrapper />
            <Providers settings={settings}>
              <ConditionalLayout settings={settings}>
                {children}
              </ConditionalLayout>
            </Providers>
          </SessionProvider>
        </LenisScrollWrapper>
      </body>
    </html>
  );
}
